[package]
name = "grok-spinv"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/kurtjd/grok-emu"

[dependencies]
bitflags = "2.9.1"
grok-80 = { path = "../grok-80", features = ["i8080"] }
grok-dbg = { path = "../grok-dbg" }
grok-bus = { path = "../grok-bus" }
